Repository team-capstone-1/fe-repro-health, pull requests merged in 2023-12, with the labels that each got.

#45 (045) - refactor (authService) : change get token schema
  src/services/AuthService.js
  src/views/app-views/profile/components/DoctorProfile.jsx
  src/views/app-views/profile/components/Education.jsx
  src/views/app-views/profile/components/WorkExperience.jsx
  src/views/auth-views/Login.jsx
Labels: enhancement

#47 (047) fix : fixed bug on search features
  src/components/shared-components/Toast.jsx
  src/views/app-views/appointment/components/ListFilter.jsx
  src/views/app-views/article/components/ListArticle.jsx
  src/views/app-views/profile/components/Certificate.jsx
  src/views/app-views/profile/components/DoctorProfile.jsx
  src/views/auth-views/Login.jsx
Labels: bug

#48 (048) - feat/janji-temu : Add API integration for Appointment page
  src/apis/APIAppointment.js
  src/components/layout-components/LogoutModal.jsx
  src/components/shared-components/ModalConfirmAppointment.jsx
  src/components/shared-components/ModalPaymentAppointment.jsx
  src/store/index.js
  src/store/toggle-fetch-new-data/index.js
  src/views/app-views/appointment/components/CardAppointment.jsx
  src/views/app-views/appointment/components/DetailPatient.jsx
  src/views/app-views/appointment/components/ListAppointment.jsx
  src/views/app-views/appointment/components/ListFilter.jsx
  src/views/app-views/appointment/components/SkeletonDetailPatient.jsx
  src/views/app-views/appointment/constant/appointment/index.jsx
  src/views/app-views/appointment/constant/detail-pasien/index.js
Labels: enhancement

#49 (049) - feat : add global route utility and set navigate on logout
  src/apis/APIAuth.js
  src/components/layout-components/LogoutModal.jsx
  src/routers/index.jsx
  src/utils/GlobalRoute.js
Labels: enhancement

#52 (052) - fix/auth-views
  src/assets/blank-profile.png
  src/components/layout-components/AppLayout.jsx
  src/components/layout-components/Topbar.jsx
  src/hooks/useDocumentTitle.jsx
  src/routers/ProtectedRoute.jsx
  src/routers/index.jsx
  src/store/index.js
  src/store/is-password-reset-slice/index.js
  src/views/app-views/article/components/UploadArticle.jsx
  src/views/app-views/profile/components/DoctorProfile.jsx
  src/views/auth-views/ForgotPassword.jsx
  src/views/auth-views/Login.jsx
  src/views/auth-views/ResetPassword.jsx
  src/views/auth-views/Verify.jsx
  src/views/landing-views/index.jsx
Labels: enhancement

#53 (053) - fix/auth-views
  src/components/layout-components/AppLayout.jsx
  src/routers/PrivateAndProtectedRoute.jsx
  src/routers/index.jsx
  src/services/AuthService.js
  src/views/auth-views/ResetPassword.jsx
  src/views/auth-views/Verify.jsx
Labels: enhancement

#54 (054) feat: (Dashboard) api integration dashboard
  src/apis/APIDashboard.js
  src/services/AuthService.js
  src/views/app-views/article/constant/detail-article/index.js
  src/views/app-views/dashboard/components/AppointmentTable.jsx
  src/views/app-views/dashboard/components/ChartIncome.jsx
  src/views/app-views/dashboard/components/TotalCards.jsx
  src/views/app-views/dashboard/constant/appointment/index.jsx
  src/views/app-views/dashboard/constant/graph-income/index.js
  src/views/app-views/dashboard/index.jsx
Labels: enhancement

#55 (055) fix: (Dashboard) API Integration for Dashboard Cards
  src/components/shared-components/Toast.jsx
  src/views/app-views/article/components/ListArticle.jsx
  src/views/app-views/dashboard/components/AppointmentTable.jsx
  src/views/app-views/dashboard/components/TotalCards.jsx
Labels: enhancement

#63 (063) feat : my-schedule
  src/apis/APISchedule.js
  src/store/get-doctor-schedule-slice/index.js
  src/store/index.js
  src/utils/GetListData.js
  src/utils/MapListData.js
  src/views/app-views/dashboard/components/MonthlyCalendar.jsx
  src/views/app-views/my-schedule/components/ButtonSubmit.jsx
  src/views/app-views/my-schedule/components/DetailSchedule.jsx
  src/views/app-views/my-schedule/components/Indicator.jsx
  src/views/app-views/my-schedule/components/ListAppointment.jsx
  src/views/app-views/my-schedule/components/ScheduleCalendar.jsx
  src/views/app-views/my-schedule/constant/my-schedule/NewResponse.js
Labels: enhancement

#64 (064) refactor:(ListArticles) fixing bug on search value, also add no data found
  src/views/app-views/article/components/ListArticle.jsx
Labels: bug, enhancement

#65 (065) fix:(TotalCards) add initial value in total cards when data not found
  src/apis/APIDashboard.js
  src/components/layout-components/Footer.jsx
  src/components/layout-components/Topbar.jsx
  src/components/shared-components/BannerDownload.jsx
  src/views/app-views/appointment/components/CardAppointment.jsx
  src/views/app-views/appointment/components/DetailPatient.jsx
  src/views/app-views/chatbot/index.jsx
  src/views/app-views/dashboard/components/ChartIncome.jsx
  src/views/app-views/dashboard/components/TotalCards.jsx
  src/views/app-views/dashboard/constant/graph-income/index.js
  src/views/app-views/forum/components/AllDiscussion.jsx
  src/views/app-views/forum/misc/DiscussionDetail.jsx
  src/views/app-views/profile/components/DoctorProfile.jsx
Labels: bug, enhancement

#69 (069) refactor:(Chart Income) dashboard
  src/utils/FormatDate.js
  src/views/app-views/dashboard/components/AppointmentTable.jsx
  src/views/app-views/dashboard/components/ChartIncome.jsx
  src/views/app-views/dashboard/constant/graph-income/index.js
Labels: enhancement

#70 (070) fix: (Dashboard) fixing percent and refactor toLocaleString
  src/views/app-views/dashboard/components/ChartIncome.jsx
  src/views/app-views/dashboard/components/TotalCards.jsx
Labels: enhancement

#71 (071) - Feat/my schedule
  src/apis/APISchedule.js
  src/components/layout-components/Topbar.jsx
  src/components/shared-components/ModalConfirmSchedule.jsx
  src/views/app-views/article/misc/DetailArticle.jsx
  src/views/app-views/chatbot/index.jsx
  src/views/app-views/forum/misc/DiscussionDetail.jsx
  src/views/app-views/my-schedule/components/DetailSchedule.jsx
  src/views/app-views/my-schedule/components/ScheduleCalendar.jsx
  src/views/app-views/profile/constant/certificate/index.jsx
Labels: enhancement

#72 (072) feat: (Article) add pagination article, also fixing format week (Chart)
  src/utils/FormatDate.js
  src/views/app-views/article/components/ListArticle.jsx
  src/views/app-views/dashboard/components/ChartIncome.jsx
  src/views/app-views/dashboard/components/TotalCards.jsx
  src/views/app-views/dashboard/index.jsx
Labels: enhancement

#79 (079) fix: (CommentArticle)
  src/views/app-views/article/constant/detail-article/index.js
  src/views/app-views/article/misc/DetailArticle.jsx
  src/views/app-views/dashboard/components/ButtonFilter.jsx
  src/views/app-views/profile/constant/certificate/index.jsx
Labels: enhancement
